// WITH_STDLIB

/*
 * KOTLIN CODEGEN BOX SPEC TEST (POSITIVE)
 *
 * SPEC VERSION: 1.9-rfc+0.1
 * MAIN LINK: type-system, introduction-1 -> paragraph 5 -> sentence 2
 * NUMBER: 2
 * DESCRIPTION: The use of Boolean literals as the identifier (with backtick) in the class.
 * NOTE: this test data is generated by FeatureInteractionTestDataGenerator. DO NOT MODIFY CODE MANUALLY
 */
// TESTCASE NUMBER: 1
class `true` {
    val `false` = true
}

class `false` {
    val `true` = false
}

fun box(): String {
    val instance1 = `true`()
    val instance2 = `false`()
    return if (instance1.`false` == true && instance2.`true` == false) "OK" else "NOK"
}