/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.EnforcedProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.ClassLevelProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/sanitizer/tbi")
@TestDataPath("$PROJECT_ROOT")
@Tag("sanitizer-tbi")
@EnforcedProperty(property = ClassLevelProperty.TEST_KIND, propertyValue = "STANDALONE_NO_TR")
@EnforcedProperty(property = ClassLevelProperty.CACHE_MODE, propertyValue = "NO")
@EnforcedProperty(property = ClassLevelProperty.GC_TYPE, propertyValue = "CMS")
@EnforcedProperty(property = ClassLevelProperty.ALLOCATOR, propertyValue = "CUSTOM")
@EnforcedProperty(property = ClassLevelProperty.PAGED_ALLOCATOR, propertyValue = "FALSE")
@EnforcedProperty(property = ClassLevelProperty.SANITIZER, propertyValue = "HWADDRESS")
@UseStandardTestCaseGroupProvider()
public class FirSanitizerTbiCmsCustomPagedFalseHwaddressTestGenerated extends AbstractSanitizerBlackBoxTest {
  @Test
  public void testAllFilesPresentInTbi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/sanitizer/tbi"), Pattern.compile("^(.+)\\.kt$"), null, false);
  }

  @Test
  @TestMetadata("extraobject_typeinfo_hwasan_fp.kt")
  public void testExtraobject_typeinfo_hwasan_fp() {
    runTest("native/native.tests/testData/sanitizer/tbi/extraobject_typeinfo_hwasan_fp.kt");
  }

  @Test
  @TestMetadata("forward_dynamic.kt")
  public void testForward_dynamic() {
    runTest("native/native.tests/testData/sanitizer/tbi/forward_dynamic.kt");
  }

  @Test
  @TestMetadata("language_dynamic.kt")
  public void testLanguage_dynamic() {
    runTest("native/native.tests/testData/sanitizer/tbi/language_dynamic.kt");
  }

  @Test
  @TestMetadata("refield_struct_marker.kt")
  public void testRefield_struct_marker() {
    runTest("native/native.tests/testData/sanitizer/tbi/refield_struct_marker.kt");
  }

  @Test
  @TestMetadata("valid_bit_crt_default.kt")
  public void testValid_bit_crt_default() {
    runTest("native/native.tests/testData/sanitizer/tbi/valid_bit_crt_default.kt");
  }

  @Test
  @TestMetadata("weak_dynamic.kt")
  public void testWeak_dynamic() {
    runTest("native/native.tests/testData/sanitizer/tbi/weak_dynamic.kt");
  }

  @Test
  @TestMetadata("x28_dynamic_ok.kt")
  public void testX28_dynamic_ok() {
    runTest("native/native.tests/testData/sanitizer/tbi/x28_dynamic_ok.kt");
  }

  @Test
  @TestMetadata("x28_hwasan_conflict.kt")
  public void testX28_hwasan_conflict() {
    runTest("native/native.tests/testData/sanitizer/tbi/x28_hwasan_conflict.kt");
  }

  @Test
  @TestMetadata("x28_std_single_ok.kt")
  public void testX28_std_single_ok() {
    runTest("native/native.tests/testData/sanitizer/tbi/x28_std_single_ok.kt");
  }
}
