/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.EnforcedProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.ClassLevelProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/sanitizer/corruption")
@TestDataPath("$PROJECT_ROOT")
@Tag("sanitizer-corruption")
@EnforcedProperty(property = ClassLevelProperty.TEST_KIND, propertyValue = "STANDALONE_NO_TR")
@EnforcedProperty(property = ClassLevelProperty.CACHE_MODE, propertyValue = "NO")
@EnforcedProperty(property = ClassLevelProperty.GC_TYPE, propertyValue = "CMS")
@EnforcedProperty(property = ClassLevelProperty.ALLOCATOR, propertyValue = "CUSTOM")
@EnforcedProperty(property = ClassLevelProperty.PAGED_ALLOCATOR, propertyValue = "FALSE")
@EnforcedProperty(property = ClassLevelProperty.SANITIZER, propertyValue = "ADDRESS")
@UseStandardTestCaseGroupProvider()
public class FirSanitizerCorruptionCmsCustomPagedFalseAddressTestGenerated extends AbstractSanitizerBlackBoxTest {
  @Test
  public void testAllFilesPresentInCorruption() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/sanitizer/corruption"), Pattern.compile("^(.+)\\.kt$"), null, false);
  }

  @Test
  @TestMetadata("cGlobal_kotlin_overflowWrite.kt")
  public void testCGlobal_kotlin_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/cGlobal_kotlin_overflowWrite.kt");
  }

  @Test
  @TestMetadata("cStack_cDefinition_stackUseAfterReturn.kt")
  public void testCStack_cDefinition_stackUseAfterReturn() {
    runTest("native/native.tests/testData/sanitizer/corruption/cStack_cDefinition_stackUseAfterReturn.kt");
  }

  @Test
  @TestMetadata("invalidAddress_kotlin_wildPointerWrite.kt")
  public void testInvalidAddress_kotlin_wildPointerWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/invalidAddress_kotlin_wildPointerWrite.kt");
  }

  @Test
  @TestMetadata("kotlinHeapHashMap_kotlinWorkers_useAfterFree.kt")
  public void testKotlinHeapHashMap_kotlinWorkers_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapHashMap_kotlinWorkers_useAfterFree.kt");
  }

  @Test
  @TestMetadata("kotlinHeapPinned_cDefinition_overflowWrite.kt")
  public void testKotlinHeapPinned_cDefinition_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapPinned_cDefinition_overflowWrite.kt");
  }

  @Test
  @TestMetadata("kotlinHeapPinned_kotlin_overflowWrite.kt")
  public void testKotlinHeapPinned_kotlin_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapPinned_kotlin_overflowWrite.kt");
  }

  @Test
  @TestMetadata("kotlinHeapPinned_platformPosix_invalidFree.kt")
  public void testKotlinHeapPinned_platformPosix_invalidFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapPinned_platformPosix_invalidFree.kt");
  }

  @Test
  @TestMetadata("kotlinHeapPinned_platformPosix_overflowWrite.kt")
  public void testKotlinHeapPinned_platformPosix_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapPinned_platformPosix_overflowWrite.kt");
  }

  @Test
  @TestMetadata("kotlinHeapStableRef_kotlinCallback_useAfterFree.kt")
  public void testKotlinHeapStableRef_kotlinCallback_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapStableRef_kotlinCallback_useAfterFree.kt");
  }

  @Test
  @TestMetadata("kotlinHeapStableRef_kotlin_useAfterFree.kt")
  public void testKotlinHeapStableRef_kotlin_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/kotlinHeapStableRef_kotlin_useAfterFree.kt");
  }

  @Test
  @TestMetadata("mallocHeap_cDefinition_doubleFree.kt")
  public void testMallocHeap_cDefinition_doubleFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_cDefinition_doubleFree.kt");
  }

  @Test
  @TestMetadata("mallocHeap_cDefinition_overflowWrite.kt")
  public void testMallocHeap_cDefinition_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_cDefinition_overflowWrite.kt");
  }

  @Test
  @TestMetadata("mallocHeap_kotlinCallback_useAfterFree.kt")
  public void testMallocHeap_kotlinCallback_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_kotlinCallback_useAfterFree.kt");
  }

  @Test
  @TestMetadata("mallocHeap_kotlin_overflowWrite.kt")
  public void testMallocHeap_kotlin_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_kotlin_overflowWrite.kt");
  }

  @Test
  @TestMetadata("mallocHeap_kotlin_useAfterRealloc.kt")
  public void testMallocHeap_kotlin_useAfterRealloc() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_kotlin_useAfterRealloc.kt");
  }

  @Test
  @TestMetadata("mallocHeap_nativeHeapThenPlatform_doubleFree.kt")
  public void testMallocHeap_nativeHeapThenPlatform_doubleFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_nativeHeapThenPlatform_doubleFree.kt");
  }

  @Test
  @TestMetadata("mallocHeap_platformPosix_invalidFree_interior.kt")
  public void testMallocHeap_platformPosix_invalidFree_interior() {
    runTest("native/native.tests/testData/sanitizer/corruption/mallocHeap_platformPosix_invalidFree_interior.kt");
  }

  @Test
  @TestMetadata("memScoped_cDefinition_invalidFree.kt")
  public void testMemScoped_cDefinition_invalidFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/memScoped_cDefinition_invalidFree.kt");
  }

  @Test
  @TestMetadata("memScoped_kotlin_useAfterFree.kt")
  public void testMemScoped_kotlin_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/memScoped_kotlin_useAfterFree.kt");
  }

  @Test
  @TestMetadata("nativeHeap_cDefinition_overflowWrite.kt")
  public void testNativeHeap_cDefinition_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_cDefinition_overflowWrite.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlinCallback_overflowWrite.kt")
  public void testNativeHeap_kotlinCallback_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlinCallback_overflowWrite.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlinNativeRuntime_overflowRead.kt")
  public void testNativeHeap_kotlinNativeRuntime_overflowRead() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlinNativeRuntime_overflowRead.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_overflowRead.kt")
  public void testNativeHeap_kotlin_overflowRead() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_overflowRead.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_overflowWrite.kt")
  public void testNativeHeap_kotlin_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_overflowWrite.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_overflowWrite_allocationSizeWrap.kt")
  public void testNativeHeap_kotlin_overflowWrite_allocationSizeWrap() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_overflowWrite_allocationSizeWrap.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_underflowRead.kt")
  public void testNativeHeap_kotlin_underflowRead() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_underflowRead.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_underflowWrite.kt")
  public void testNativeHeap_kotlin_underflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_underflowWrite.kt");
  }

  @Test
  @TestMetadata("nativeHeap_kotlin_useAfterFree.kt")
  public void testNativeHeap_kotlin_useAfterFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_kotlin_useAfterFree.kt");
  }

  @Test
  @TestMetadata("nativeHeap_nativeHeapFree_doubleFree.kt")
  public void testNativeHeap_nativeHeapFree_doubleFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_nativeHeapFree_doubleFree.kt");
  }

  @Test
  @TestMetadata("nativeHeap_platformThenNativeHeap_doubleFree.kt")
  public void testNativeHeap_platformThenNativeHeap_doubleFree() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_platformThenNativeHeap_doubleFree.kt");
  }

  @Test
  @TestMetadata("nativeHeap_toKString_overflowRead.kt")
  public void testNativeHeap_toKString_overflowRead() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_toKString_overflowRead.kt");
  }

  @Test
  @TestMetadata("nativeHeap_writeBits_overflowWrite.kt")
  public void testNativeHeap_writeBits_overflowWrite() {
    runTest("native/native.tests/testData/sanitizer/corruption/nativeHeap_writeBits_overflowWrite.kt");
  }
}
