/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.ClassicPipeline;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/gc")
@TestDataPath("$PROJECT_ROOT")
@Tag("gc")
@UseStandardTestCaseGroupProvider()
@ClassicPipeline()
public class NativeGCTestGenerated extends AbstractNativeBlackBoxTest {
  @Test
  public void testAllFilesPresentInGc() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/gc"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("basic0.kt")
  public void testBasic0() {
    runTest("native/native.tests/testData/gc/basic0.kt");
  }

  @Test
  @TestMetadata("cleaner_basic.kt")
  public void testCleaner_basic() {
    runTest("native/native.tests/testData/gc/cleaner_basic.kt");
  }

  @Test
  @TestMetadata("cleaner_in_tls_worker.kt")
  public void testCleaner_in_tls_worker() {
    runTest("native/native.tests/testData/gc/cleaner_in_tls_worker.kt");
  }

  @Test
  @TestMetadata("cleaner_workers.kt")
  public void testCleaner_workers() {
    runTest("native/native.tests/testData/gc/cleaner_workers.kt");
  }

  @Test
  @TestMetadata("collect.kt")
  public void testCollect() {
    runTest("native/native.tests/testData/gc/collect.kt");
  }

  @Test
  @TestMetadata("crt_array_read_barrier.kt")
  public void testCrt_array_read_barrier() {
    runTest("native/native.tests/testData/gc/crt_array_read_barrier.kt");
  }

  @Test
  @TestMetadata("crt_boundary_frame.kt")
  public void testCrt_boundary_frame() {
    runTest("native/native.tests/testData/gc/crt_boundary_frame.kt");
  }

  @Test
  @TestMetadata("crt_cached_boxed_value.kt")
  public void testCrt_cached_boxed_value() {
    runTest("native/native.tests/testData/gc/crt_cached_boxed_value.kt");
  }

  @Test
  @TestMetadata("crt_cinterop_boundary.kt")
  public void testCrt_cinterop_boundary() {
    runTest("native/native.tests/testData/gc/crt_cinterop_boundary.kt");
  }

  @Test
  @TestMetadata("crt_circular_reference_stress.kt")
  public void testCrt_circular_reference_stress() {
    runTest("native/native.tests/testData/gc/crt_circular_reference_stress.kt");
  }

  @Test
  @TestMetadata("crt_cleaner_complex_graph.kt")
  public void testCrt_cleaner_complex_graph() {
    runTest("native/native.tests/testData/gc/crt_cleaner_complex_graph.kt");
  }

  @Test
  @TestMetadata("crt_compaction_verify.kt")
  public void testCrt_compaction_verify() {
    runTest("native/native.tests/testData/gc/crt_compaction_verify.kt");
  }

  @Test
  @TestMetadata("crt_concurrent_data_structures.kt")
  public void testCrt_concurrent_data_structures() {
    runTest("native/native.tests/testData/gc/crt_concurrent_data_structures.kt");
  }

  @Test
  @TestMetadata("crt_concurrent_mutation.kt")
  public void testCrt_concurrent_mutation() {
    runTest("native/native.tests/testData/gc/crt_concurrent_mutation.kt");
  }

  @Test
  @TestMetadata("crt_daemon_shutdown.kt")
  public void testCrt_daemon_shutdown() {
    runTest("native/native.tests/testData/gc/crt_daemon_shutdown.kt");
  }

  @Test
  @TestMetadata("crt_deep_recursion_gc.kt")
  public void testCrt_deep_recursion_gc() {
    runTest("native/native.tests/testData/gc/crt_deep_recursion_gc.kt");
  }

  @Test
  @TestMetadata("crt_deep_stack_scan.kt")
  public void testCrt_deep_stack_scan() {
    runTest("native/native.tests/testData/gc/crt_deep_stack_scan.kt");
  }

  @Test
  @TestMetadata("crt_exception_deep_nesting.kt")
  public void testCrt_exception_deep_nesting() {
    runTest("native/native.tests/testData/gc/crt_exception_deep_nesting.kt");
  }

  @Test
  @TestMetadata("crt_field_forwarding.kt")
  public void testCrt_field_forwarding() {
    runTest("native/native.tests/testData/gc/crt_field_forwarding.kt");
  }

  @Test
  @TestMetadata("crt_finalizer_ordering.kt")
  public void testCrt_finalizer_ordering() {
    runTest("native/native.tests/testData/gc/crt_finalizer_ordering.kt");
  }

  @Test
  @TestMetadata("crt_gc_during_init.kt")
  public void testCrt_gc_during_init() {
    runTest("native/native.tests/testData/gc/crt_gc_during_init.kt");
  }

  @Test
  @TestMetadata("crt_global_roots_concurrent.kt")
  public void testCrt_global_roots_concurrent() {
    runTest("native/native.tests/testData/gc/crt_global_roots_concurrent.kt");
  }

  @Test
  @TestMetadata("crt_k2n_boundary_stress.kt")
  public void testCrt_k2n_boundary_stress() {
    runTest("native/native.tests/testData/gc/crt_k2n_boundary_stress.kt");
  }

  @Test
  @TestMetadata("crt_large_object_stress.kt")
  public void testCrt_large_object_stress() {
    runTest("native/native.tests/testData/gc/crt_large_object_stress.kt");
  }

  @Test
  @TestMetadata("crt_pinning_stress.kt")
  public void testCrt_pinning_stress() {
    runTest("native/native.tests/testData/gc/crt_pinning_stress.kt");
  }

  @Test
  @TestMetadata("crt_r2k_boundary.kt")
  public void testCrt_r2k_boundary() {
    runTest("native/native.tests/testData/gc/crt_r2k_boundary.kt");
  }

  @Test
  @TestMetadata("crt_rapid_gc_cycle.kt")
  public void testCrt_rapid_gc_cycle() {
    runTest("native/native.tests/testData/gc/crt_rapid_gc_cycle.kt");
  }

  @Test
  @TestMetadata("crt_stable_ref_lifecycle.kt")
  public void testCrt_stable_ref_lifecycle() {
    runTest("native/native.tests/testData/gc/crt_stable_ref_lifecycle.kt");
  }

  @Test
  @TestMetadata("crt_string_boundary.kt")
  public void testCrt_string_boundary() {
    runTest("native/native.tests/testData/gc/crt_string_boundary.kt");
  }

  @Test
  @TestMetadata("crt_weakref_clearing_timing.kt")
  public void testCrt_weakref_clearing_timing() {
    runTest("native/native.tests/testData/gc/crt_weakref_clearing_timing.kt");
  }

  @Test
  @TestMetadata("crt_worker_lifecycle_stress.kt")
  public void testCrt_worker_lifecycle_stress() {
    runTest("native/native.tests/testData/gc/crt_worker_lifecycle_stress.kt");
  }

  @Test
  @TestMetadata("cycles0.kt")
  public void testCycles0() {
    runTest("native/native.tests/testData/gc/cycles0.kt");
  }

  @Test
  @TestMetadata("cycles1.kt")
  public void testCycles1() {
    runTest("native/native.tests/testData/gc/cycles1.kt");
  }

  @Test
  @TestMetadata("escape0.kt")
  public void testEscape0() {
    runTest("native/native.tests/testData/gc/escape0.kt");
  }

  @Test
  @TestMetadata("escape1.kt")
  public void testEscape1() {
    runTest("native/native.tests/testData/gc/escape1.kt");
  }

  @Test
  @TestMetadata("escape2.kt")
  public void testEscape2() {
    runTest("native/native.tests/testData/gc/escape2.kt");
  }

  @Test
  @TestMetadata("ExternalRCRefTest.kt")
  public void testExternalRCRefTest() {
    runTest("native/native.tests/testData/gc/ExternalRCRefTest.kt");
  }

  @Test
  @TestMetadata("gcStats.kt")
  public void testGcStats() {
    runTest("native/native.tests/testData/gc/gcStats.kt");
  }

  @Test
  @TestMetadata("lazy2.kt")
  public void testLazy2() {
    runTest("native/native.tests/testData/gc/lazy2.kt");
  }

  @Test
  @TestMetadata("lazy3.kt")
  public void testLazy3() {
    runTest("native/native.tests/testData/gc/lazy3.kt");
  }

  @Test
  @TestMetadata("memoryDump.kt")
  public void testMemoryDump() {
    runTest("native/native.tests/testData/gc/memoryDump.kt");
  }

  @Test
  @TestMetadata("throwable.kt")
  public void testThrowable() {
    runTest("native/native.tests/testData/gc/throwable.kt");
  }

  @Test
  @TestMetadata("weak0.kt")
  public void testWeak0() {
    runTest("native/native.tests/testData/gc/weak0.kt");
  }

  @Test
  @TestMetadata("weak1.kt")
  public void testWeak1() {
    runTest("native/native.tests/testData/gc/weak1.kt");
  }

  @Test
  @TestMetadata("worker10.kt")
  public void testWorker10() {
    runTest("native/native.tests/testData/gc/worker10.kt");
  }

  @Test
  @TestMetadata("workerCancelJobsWithGC.kt")
  public void testWorkerCancelJobsWithGC() {
    runTest("native/native.tests/testData/gc/workerCancelJobsWithGC.kt");
  }

  @Test
  @TestMetadata("worker_bound_reference0.kt")
  public void testWorker_bound_reference0() {
    runTest("native/native.tests/testData/gc/worker_bound_reference0.kt");
  }
}
