/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/gc/crt")
@TestDataPath("$PROJECT_ROOT")
@Tag("crt-gc")
@UseStandardTestCaseGroupProvider()
public class NativeCrtGCTestGenerated extends AbstractNativeBlackBoxTest {
  @Test
  public void testAllFilesPresentInCrt() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/gc/crt"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("crt_array_element_barrier.kt")
  public void testCrt_array_element_barrier() {
    runTest("native/native.tests/testData/gc/crt/crt_array_element_barrier.kt");
  }

  @Test
  @TestMetadata("crt_array_fill_barrier.kt")
  public void testCrt_array_fill_barrier() {
    runTest("native/native.tests/testData/gc/crt/crt_array_fill_barrier.kt");
  }

  @Test
  @TestMetadata("crt_array_read_barrier.kt")
  public void testCrt_array_read_barrier() {
    runTest("native/native.tests/testData/gc/crt/crt_array_read_barrier.kt");
  }

  @Test
  @TestMetadata("crt_array_sort_gc.kt")
  public void testCrt_array_sort_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_array_sort_gc.kt");
  }

  @Test
  @TestMetadata("crt_boundary_frame.kt")
  public void testCrt_boundary_frame() {
    runTest("native/native.tests/testData/gc/crt/crt_boundary_frame.kt");
  }

  @Test
  @TestMetadata("crt_cached_boxed_value.kt")
  public void testCrt_cached_boxed_value() {
    runTest("native/native.tests/testData/gc/crt/crt_cached_boxed_value.kt");
  }

  @Test
  @TestMetadata("crt_cinterop_boundary.kt")
  public void testCrt_cinterop_boundary() {
    runTest("native/native.tests/testData/gc/crt/crt_cinterop_boundary.kt");
  }

  @Test
  @TestMetadata("crt_circular_reference_stress.kt")
  public void testCrt_circular_reference_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_circular_reference_stress.kt");
  }

  @Test
  @TestMetadata("crt_cleaner_complex_graph.kt")
  public void testCrt_cleaner_complex_graph() {
    runTest("native/native.tests/testData/gc/crt/crt_cleaner_complex_graph.kt");
  }

  @Test
  @TestMetadata("crt_compacting_gc_patterns.kt")
  public void testCrt_compacting_gc_patterns() {
    runTest("native/native.tests/testData/gc/crt/crt_compacting_gc_patterns.kt");
  }

  @Test
  @TestMetadata("crt_compaction_verify.kt")
  public void testCrt_compaction_verify() {
    runTest("native/native.tests/testData/gc/crt/crt_compaction_verify.kt");
  }

  @Test
  @TestMetadata("crt_concurrent_data_structures.kt")
  public void testCrt_concurrent_data_structures() {
    runTest("native/native.tests/testData/gc/crt/crt_concurrent_data_structures.kt");
  }

  @Test
  @TestMetadata("crt_concurrent_mutation.kt")
  public void testCrt_concurrent_mutation() {
    runTest("native/native.tests/testData/gc/crt/crt_concurrent_mutation.kt");
  }

  @Test
  @TestMetadata("crt_conservative_gc_patterns.kt")
  public void testCrt_conservative_gc_patterns() {
    runTest("native/native.tests/testData/gc/crt/crt_conservative_gc_patterns.kt");
  }

  @Test
  @TestMetadata("crt_daemon_shutdown.kt")
  public void testCrt_daemon_shutdown() {
    runTest("native/native.tests/testData/gc/crt/crt_daemon_shutdown.kt");
  }

  @Test
  @TestMetadata("crt_daemon_stress.kt")
  public void testCrt_daemon_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_daemon_stress.kt");
  }

  @Test
  @TestMetadata("crt_dead_large_object.kt")
  public void testCrt_dead_large_object() {
    runTest("native/native.tests/testData/gc/crt/crt_dead_large_object.kt");
  }

  @Test
  @TestMetadata("crt_deep_recursion_gc.kt")
  public void testCrt_deep_recursion_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_deep_recursion_gc.kt");
  }

  @Test
  @TestMetadata("crt_deep_stack_scan.kt")
  public void testCrt_deep_stack_scan() {
    runTest("native/native.tests/testData/gc/crt/crt_deep_stack_scan.kt");
  }

  @Test
  @TestMetadata("crt_enum_delegate_gc.kt")
  public void testCrt_enum_delegate_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_enum_delegate_gc.kt");
  }

  @Test
  @TestMetadata("crt_exception_deep_nesting.kt")
  public void testCrt_exception_deep_nesting() {
    runTest("native/native.tests/testData/gc/crt/crt_exception_deep_nesting.kt");
  }

  @Test
  @TestMetadata("crt_field_forwarding.kt")
  public void testCrt_field_forwarding() {
    runTest("native/native.tests/testData/gc/crt/crt_field_forwarding.kt");
  }

  @Test
  @TestMetadata("crt_finalizer_ordering.kt")
  public void testCrt_finalizer_ordering() {
    runTest("native/native.tests/testData/gc/crt/crt_finalizer_ordering.kt");
  }

  @Test
  @TestMetadata("crt_finals_publication.kt")
  public void testCrt_finals_publication() {
    runTest("native/native.tests/testData/gc/crt/crt_finals_publication.kt");
  }

  @Test
  @TestMetadata("crt_gc_during_init.kt")
  public void testCrt_gc_during_init() {
    runTest("native/native.tests/testData/gc/crt/crt_gc_during_init.kt");
  }

  @Test
  @TestMetadata("crt_gc_thrash.kt")
  public void testCrt_gc_thrash() {
    runTest("native/native.tests/testData/gc/crt/crt_gc_thrash.kt");
  }

  @Test
  @TestMetadata("crt_gcold_write_barrier.kt")
  public void testCrt_gcold_write_barrier() {
    runTest("native/native.tests/testData/gc/crt/crt_gcold_write_barrier.kt");
  }

  @Test
  @TestMetadata("crt_global_roots_concurrent.kt")
  public void testCrt_global_roots_concurrent() {
    runTest("native/native.tests/testData/gc/crt/crt_global_roots_concurrent.kt");
  }

  @Test
  @TestMetadata("crt_hashmap_resize_gc.kt")
  public void testCrt_hashmap_resize_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_hashmap_resize_gc.kt");
  }

  @Test
  @TestMetadata("crt_inline_class_gc.kt")
  public void testCrt_inline_class_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_inline_class_gc.kt");
  }

  @Test
  @TestMetadata("crt_interface_dispatch_gc.kt")
  public void testCrt_interface_dispatch_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_interface_dispatch_gc.kt");
  }

  @Test
  @TestMetadata("crt_iterator_sequence_gc.kt")
  public void testCrt_iterator_sequence_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_iterator_sequence_gc.kt");
  }

  @Test
  @TestMetadata("crt_k2n_boundary_stress.kt")
  public void testCrt_k2n_boundary_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_k2n_boundary_stress.kt");
  }

  @Test
  @TestMetadata("crt_lambda_capture_gc.kt")
  public void testCrt_lambda_capture_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_lambda_capture_gc.kt");
  }

  @Test
  @TestMetadata("crt_large_object_stress.kt")
  public void testCrt_large_object_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_large_object_stress.kt");
  }

  @Test
  @TestMetadata("crt_lock_contention_gc.kt")
  public void testCrt_lock_contention_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_lock_contention_gc.kt");
  }

  @Test
  @TestMetadata("crt_lost_object.kt")
  public void testCrt_lost_object() {
    runTest("native/native.tests/testData/gc/crt/crt_lost_object.kt");
  }

  @Test
  @TestMetadata("crt_memory_ordering_litmus.kt")
  public void testCrt_memory_ordering_litmus() {
    runTest("native/native.tests/testData/gc/crt/crt_memory_ordering_litmus.kt");
  }

  @Test
  @TestMetadata("crt_mixed_thread_gc.kt")
  public void testCrt_mixed_thread_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_mixed_thread_gc.kt");
  }

  @Test
  @TestMetadata("crt_oom_fragmentation.kt")
  public void testCrt_oom_fragmentation() {
    runTest("native/native.tests/testData/gc/crt/crt_oom_fragmentation.kt");
  }

  @Test
  @TestMetadata("crt_pin_generational_stress.kt")
  public void testCrt_pin_generational_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_pin_generational_stress.kt");
  }

  @Test
  @TestMetadata("crt_pin_rawpointer_region.kt")
  public void testCrt_pin_rawpointer_region() {
    runTest("native/native.tests/testData/gc/crt/crt_pin_rawpointer_region.kt");
  }

  @Test
  @TestMetadata("crt_pinning_stress.kt")
  public void testCrt_pinning_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_pinning_stress.kt");
  }

  @Test
  @TestMetadata("crt_precise_gc.kt")
  public void testCrt_precise_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_precise_gc.kt");
  }

  @Test
  @TestMetadata("crt_publication_safety.kt")
  public void testCrt_publication_safety() {
    runTest("native/native.tests/testData/gc/crt/crt_publication_safety.kt");
  }

  @Test
  @TestMetadata("crt_r2k_boundary.kt")
  public void testCrt_r2k_boundary() {
    runTest("native/native.tests/testData/gc/crt/crt_r2k_boundary.kt");
  }

  @Test
  @TestMetadata("crt_rapid_gc_cycle.kt")
  public void testCrt_rapid_gc_cycle() {
    runTest("native/native.tests/testData/gc/crt/crt_rapid_gc_cycle.kt");
  }

  @Test
  @TestMetadata("crt_regex_channel_gc.kt")
  public void testCrt_regex_channel_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_regex_channel_gc.kt");
  }

  @Test
  @TestMetadata("crt_rmw_barrier_stress.kt")
  public void testCrt_rmw_barrier_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_rmw_barrier_stress.kt");
  }

  @Test
  @TestMetadata("crt_stable_ref_lifecycle.kt")
  public void testCrt_stable_ref_lifecycle() {
    runTest("native/native.tests/testData/gc/crt/crt_stable_ref_lifecycle.kt");
  }

  @Test
  @TestMetadata("crt_stackmap_edge_cases.kt")
  public void testCrt_stackmap_edge_cases() {
    runTest("native/native.tests/testData/gc/crt/crt_stackmap_edge_cases.kt");
  }

  @Test
  @TestMetadata("crt_stale_bss_global_init.kt")
  public void testCrt_stale_bss_global_init() {
    runTest("native/native.tests/testData/gc/crt/crt_stale_bss_global_init.kt");
  }

  @Test
  @TestMetadata("crt_string_boundary.kt")
  public void testCrt_string_boundary() {
    runTest("native/native.tests/testData/gc/crt/crt_string_boundary.kt");
  }

  @Test
  @TestMetadata("crt_weakref_clearing_timing.kt")
  public void testCrt_weakref_clearing_timing() {
    runTest("native/native.tests/testData/gc/crt/crt_weakref_clearing_timing.kt");
  }

  @Test
  @TestMetadata("crt_weakref_mass_clearing.kt")
  public void testCrt_weakref_mass_clearing() {
    runTest("native/native.tests/testData/gc/crt/crt_weakref_mass_clearing.kt");
  }

  @Test
  @TestMetadata("crt_weakref_pressure.kt")
  public void testCrt_weakref_pressure() {
    runTest("native/native.tests/testData/gc/crt/crt_weakref_pressure.kt");
  }

  @Test
  @TestMetadata("crt_wide_object_gc.kt")
  public void testCrt_wide_object_gc() {
    runTest("native/native.tests/testData/gc/crt/crt_wide_object_gc.kt");
  }

  @Test
  @TestMetadata("crt_worker_lifecycle_stress.kt")
  public void testCrt_worker_lifecycle_stress() {
    runTest("native/native.tests/testData/gc/crt/crt_worker_lifecycle_stress.kt");
  }
}
