/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.EnforcedProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.ClassLevelProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/capi")
@TestDataPath("$PROJECT_ROOT")
@Tag("capi")
@EnforcedProperty(property = ClassLevelProperty.TEST_KIND, propertyValue = "STANDALONE")
@UseStandardTestCaseGroupProvider()
public class OhosCAPITestGenerated extends AbstractNativeBlackBoxTest {
  @Test
  @TestMetadata("AIPTest.kt")
  public void testAIPTest() {
    runTest("native/native.tests/testData/capi/AIPTest.kt");
  }

  @Test
  @TestMetadata("AREngineTest.kt")
  public void testAREngineTest() {
    runTest("native/native.tests/testData/capi/AREngineTest.kt");
  }

  @Test
  @TestMetadata("AVCapabilityTest.kt")
  public void testAVCapabilityTest() {
    runTest("native/native.tests/testData/capi/AVCapabilityTest.kt");
  }

  @Test
  @TestMetadata("AVDemuxerTest.kt")
  public void testAVDemuxerTest() {
    runTest("native/native.tests/testData/capi/AVDemuxerTest.kt");
  }

  @Test
  @TestMetadata("AVImageGeneratorTest.kt")
  public void testAVImageGeneratorTest() {
    runTest("native/native.tests/testData/capi/AVImageGeneratorTest.kt");
  }

  @Test
  @TestMetadata("AVMetadataExtractorTest.kt")
  public void testAVMetadataExtractorTest() {
    runTest("native/native.tests/testData/capi/AVMetadataExtractorTest.kt");
  }

  @Test
  @TestMetadata("AVMuxerTest.kt")
  public void testAVMuxerTest() {
    runTest("native/native.tests/testData/capi/AVMuxerTest.kt");
  }

  @Test
  @TestMetadata("AVPlayerTest.kt")
  public void testAVPlayerTest() {
    runTest("native/native.tests/testData/capi/AVPlayerTest.kt");
  }

  @Test
  @TestMetadata("AVRecorderTest.kt")
  public void testAVRecorderTest() {
    runTest("native/native.tests/testData/capi/AVRecorderTest.kt");
  }

  @Test
  @TestMetadata("AVScreenCaptureTest.kt")
  public void testAVScreenCaptureTest() {
    runTest("native/native.tests/testData/capi/AVScreenCaptureTest.kt");
  }

  @Test
  @TestMetadata("AVSinkBaseTest.kt")
  public void testAVSinkBaseTest() {
    runTest("native/native.tests/testData/capi/AVSinkBaseTest.kt");
  }

  @Test
  @TestMetadata("AVSourceTest.kt")
  public void testAVSourceTest() {
    runTest("native/native.tests/testData/capi/AVSourceTest.kt");
  }

  @Test
  @TestMetadata("AVTranscoderTest.kt")
  public void testAVTranscoderTest() {
    runTest("native/native.tests/testData/capi/AVTranscoderTest.kt");
  }

  @Test
  @TestMetadata("AbilityAccessControlTest.kt")
  public void testAbilityAccessControlTest() {
    runTest("native/native.tests/testData/capi/AbilityAccessControlTest.kt");
  }

  @Test
  @TestMetadata("AbilityBaseTest.kt")
  public void testAbilityBaseTest() {
    runTest("native/native.tests/testData/capi/AbilityBaseTest.kt");
  }

  @Test
  @TestMetadata("AbilityRuntimeTest.kt")
  public void testAbilityRuntimeTest() {
    runTest("native/native.tests/testData/capi/AbilityRuntimeTest.kt");
  }

  @Test
  public void testAllFilesPresentInCapi() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/capi"), Pattern.compile("^(.+)\\.kt$"), null, false);
  }

  @Test
  @TestMetadata("ArkTS_Napi_NativeModuleTest.kt")
  public void testArkTS_Napi_NativeModuleTest() {
    runTest("native/native.tests/testData/capi/ArkTS_Napi_NativeModuleTest.kt");
  }

  @Test
  @TestMetadata("ArkUI_AccessibilityTest.kt")
  public void testArkUI_AccessibilityTest() {
    runTest("native/native.tests/testData/capi/ArkUI_AccessibilityTest.kt");
  }

  @Test
  @TestMetadata("ArkUI_NativeModuleTest.kt")
  public void testArkUI_NativeModuleTest() {
    runTest("native/native.tests/testData/capi/ArkUI_NativeModuleTest.kt");
  }

  @Test
  @TestMetadata("ArkUI_RenderNodeUtilsTest.kt")
  public void testArkUI_RenderNodeUtilsTest() {
    runTest("native/native.tests/testData/capi/ArkUI_RenderNodeUtilsTest.kt");
  }

  @Test
  @TestMetadata("AssetApiTest.kt")
  public void testAssetApiTest() {
    runTest("native/native.tests/testData/capi/AssetApiTest.kt");
  }

  @Test
  @TestMetadata("AudioCodecTest.kt")
  public void testAudioCodecTest() {
    runTest("native/native.tests/testData/capi/AudioCodecTest.kt");
  }

  @Test
  @TestMetadata("AudioDecoderTest.kt")
  public void testAudioDecoderTest() {
    runTest("native/native.tests/testData/capi/AudioDecoderTest.kt");
  }

  @Test
  @TestMetadata("AudioEncoderTest.kt")
  public void testAudioEncoderTest() {
    runTest("native/native.tests/testData/capi/AudioEncoderTest.kt");
  }

  @Test
  @TestMetadata("BackgroundProcessManagerTest.kt")
  public void testBackgroundProcessManagerTest() {
    runTest("native/native.tests/testData/capi/BackgroundProcessManagerTest.kt");
  }

  @Test
  @TestMetadata("BaseDdkTest.kt")
  public void testBaseDdkTest() {
    runTest("native/native.tests/testData/capi/BaseDdkTest.kt");
  }

  @Test
  @TestMetadata("BluetoothTest.kt")
  public void testBluetoothTest() {
    runTest("native/native.tests/testData/capi/BluetoothTest.kt");
  }

  @Test
  @TestMetadata("BufferCommonTest.kt")
  public void testBufferCommonTest() {
    runTest("native/native.tests/testData/capi/BufferCommonTest.kt");
  }

  @Test
  @TestMetadata("CANNTest.kt")
  public void testCANNTest() {
    runTest("native/native.tests/testData/capi/CANNTest.kt");
  }

  @Test
  @TestMetadata("CertManagerTest.kt")
  public void testCertManagerTest() {
    runTest("native/native.tests/testData/capi/CertManagerTest.kt");
  }

  @Test
  @TestMetadata("ChildProcessTest.kt")
  public void testChildProcessTest() {
    runTest("native/native.tests/testData/capi/ChildProcessTest.kt");
  }

  @Test
  @TestMetadata("CloudDiskTest.kt")
  public void testCloudDiskTest() {
    runTest("native/native.tests/testData/capi/CloudDiskTest.kt");
  }

  @Test
  @TestMetadata("CodecBaseTest.kt")
  public void testCodecBaseTest() {
    runTest("native/native.tests/testData/capi/CodecBaseTest.kt");
  }

  @Test
  @TestMetadata("CoreTest.kt")
  public void testCoreTest() {
    runTest("native/native.tests/testData/capi/CoreTest.kt");
  }

  @Test
  @TestMetadata("CryptoAsymCipherApiTest.kt")
  public void testCryptoAsymCipherApiTest() {
    runTest("native/native.tests/testData/capi/CryptoAsymCipherApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoAsymKeyApiTest.kt")
  public void testCryptoAsymKeyApiTest() {
    runTest("native/native.tests/testData/capi/CryptoAsymKeyApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoCommonApiTest.kt")
  public void testCryptoCommonApiTest() {
    runTest("native/native.tests/testData/capi/CryptoCommonApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoDigestApiTest.kt")
  public void testCryptoDigestApiTest() {
    runTest("native/native.tests/testData/capi/CryptoDigestApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoKdfApiTest.kt")
  public void testCryptoKdfApiTest() {
    runTest("native/native.tests/testData/capi/CryptoKdfApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoKeyAgreementApiTest.kt")
  public void testCryptoKeyAgreementApiTest() {
    runTest("native/native.tests/testData/capi/CryptoKeyAgreementApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoMacApiTest.kt")
  public void testCryptoMacApiTest() {
    runTest("native/native.tests/testData/capi/CryptoMacApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoRandApiTest.kt")
  public void testCryptoRandApiTest() {
    runTest("native/native.tests/testData/capi/CryptoRandApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoSignatureApiTest.kt")
  public void testCryptoSignatureApiTest() {
    runTest("native/native.tests/testData/capi/CryptoSignatureApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoSymCipherApiTest.kt")
  public void testCryptoSymCipherApiTest() {
    runTest("native/native.tests/testData/capi/CryptoSymCipherApiTest.kt");
  }

  @Test
  @TestMetadata("CryptoSymKeyApiTest.kt")
  public void testCryptoSymKeyApiTest() {
    runTest("native/native.tests/testData/capi/CryptoSymKeyApiTest.kt");
  }

  @Test
  @TestMetadata("DeviceInfoTest.kt")
  public void testDeviceInfoTest() {
    runTest("native/native.tests/testData/capi/DeviceInfoTest.kt");
  }

  @Test
  @TestMetadata("DeviceManagerTest.kt")
  public void testDeviceManagerTest() {
    runTest("native/native.tests/testData/capi/DeviceManagerTest.kt");
  }

  @Test
  @TestMetadata("DeviceSecurityModeTest.kt")
  public void testDeviceSecurityModeTest() {
    runTest("native/native.tests/testData/capi/DeviceSecurityModeTest.kt");
  }

  @Test
  @TestMetadata("Direct_RenderTest.kt")
  public void testDirect_RenderTest() {
    runTest("native/native.tests/testData/capi/Direct_RenderTest.kt");
  }

  @Test
  @TestMetadata("DlpPermissionApiTest.kt")
  public void testDlpPermissionApiTest() {
    runTest("native/native.tests/testData/capi/DlpPermissionApiTest.kt");
  }

  @Test
  @TestMetadata("DrawingTest.kt")
  public void testDrawingTest() {
    runTest("native/native.tests/testData/capi/DrawingTest.kt");
  }

  @Test
  @TestMetadata("DrmTest.kt")
  public void testDrmTest() {
    runTest("native/native.tests/testData/capi/DrmTest.kt");
  }

  @Test
  @TestMetadata("EffectKitTest.kt")
  public void testEffectKitTest() {
    runTest("native/native.tests/testData/capi/EffectKitTest.kt");
  }

  @Test
  @TestMetadata("EglTest.kt")
  public void testEglTest() {
    runTest("native/native.tests/testData/capi/EglTest.kt");
  }

  @Test
  @TestMetadata("EnvironmentTest.kt")
  public void testEnvironmentTest() {
    runTest("native/native.tests/testData/capi/EnvironmentTest.kt");
  }

  @Test
  @TestMetadata("FASTTest.kt")
  public void testFASTTest() {
    runTest("native/native.tests/testData/capi/FASTTest.kt");
  }

  @Test
  @TestMetadata("FFRTTest.kt")
  public void testFFRTTest() {
    runTest("native/native.tests/testData/capi/FFRTTest.kt");
  }

  @Test
  @TestMetadata("FIDO2Test.kt")
  public void testFIDO2Test() {
    runTest("native/native.tests/testData/capi/FIDO2Test.kt");
  }

  @Test
  @TestMetadata("FileIOTest.kt")
  public void testFileIOTest() {
    runTest("native/native.tests/testData/capi/FileIOTest.kt");
  }

  @Test
  @TestMetadata("FileShareTest.kt")
  public void testFileShareTest() {
    runTest("native/native.tests/testData/capi/FileShareTest.kt");
  }

  @Test
  @TestMetadata("FileUriTest.kt")
  public void testFileUriTest() {
    runTest("native/native.tests/testData/capi/FileUriTest.kt");
  }

  @Test
  @TestMetadata("GameControllerTest.kt")
  public void testGameControllerTest() {
    runTest("native/native.tests/testData/capi/GameControllerTest.kt");
  }

  @Test
  @TestMetadata("GamePerformanceTest.kt")
  public void testGamePerformanceTest() {
    runTest("native/native.tests/testData/capi/GamePerformanceTest.kt");
  }

  @Test
  @TestMetadata("Gles31Test.kt")
  public void testGles31Test() {
    runTest("native/native.tests/testData/capi/Gles31Test.kt");
  }

  @Test
  @TestMetadata("Gles32Test.kt")
  public void testGles32Test() {
    runTest("native/native.tests/testData/capi/Gles32Test.kt");
  }

  @Test
  @TestMetadata("Gles3Test.kt")
  public void testGles3Test() {
    runTest("native/native.tests/testData/capi/Gles3Test.kt");
  }

  @Test
  @TestMetadata("GlescommonTest.kt")
  public void testGlescommonTest() {
    runTest("native/native.tests/testData/capi/GlescommonTest.kt");
  }

  @Test
  @TestMetadata("GlobalColorPickerTest.kt")
  public void testGlobalColorPickerTest() {
    runTest("native/native.tests/testData/capi/GlobalColorPickerTest.kt");
  }

  @Test
  @TestMetadata("GraphicsAccelerateTest.kt")
  public void testGraphicsAccelerateTest() {
    runTest("native/native.tests/testData/capi/GraphicsAccelerateTest.kt");
  }

  @Test
  @TestMetadata("HandWriteTest.kt")
  public void testHandWriteTest() {
    runTest("native/native.tests/testData/capi/HandWriteTest.kt");
  }

  @Test
  @TestMetadata("HiAppEventTest.kt")
  public void testHiAppEventTest() {
    runTest("native/native.tests/testData/capi/HiAppEventTest.kt");
  }

  @Test
  @TestMetadata("HiCollieTest.kt")
  public void testHiCollieTest() {
    runTest("native/native.tests/testData/capi/HiCollieTest.kt");
  }

  @Test
  @TestMetadata("HiDebugTest.kt")
  public void testHiDebugTest() {
    runTest("native/native.tests/testData/capi/HiDebugTest.kt");
  }

  @Test
  @TestMetadata("HiLogTest.kt")
  public void testHiLogTest() {
    runTest("native/native.tests/testData/capi/HiLogTest.kt");
  }

  @Test
  @TestMetadata("HidDdkTest.kt")
  public void testHidDdkTest() {
    runTest("native/native.tests/testData/capi/HidDdkTest.kt");
  }

  @Test
  @TestMetadata("HitraceTest.kt")
  public void testHitraceTest() {
    runTest("native/native.tests/testData/capi/HitraceTest.kt");
  }

  @Test
  @TestMetadata("HuksExternalCryptoApiTest.kt")
  public void testHuksExternalCryptoApiTest() {
    runTest("native/native.tests/testData/capi/HuksExternalCryptoApiTest.kt");
  }

  @Test
  @TestMetadata("HuksKeyApiTest.kt")
  public void testHuksKeyApiTest() {
    runTest("native/native.tests/testData/capi/HuksKeyApiTest.kt");
  }

  @Test
  @TestMetadata("HuksParamSetApiTest.kt")
  public void testHuksParamSetApiTest() {
    runTest("native/native.tests/testData/capi/HuksParamSetApiTest.kt");
  }

  @Test
  @TestMetadata("I18nTest.kt")
  public void testI18nTest() {
    runTest("native/native.tests/testData/capi/I18nTest.kt");
  }

  @Test
  @TestMetadata("IconvTest.kt")
  public void testIconvTest() {
    runTest("native/native.tests/testData/capi/IconvTest.kt");
  }

  @Test
  @TestMetadata("ImageEffectTest.kt")
  public void testImageEffectTest() {
    runTest("native/native.tests/testData/capi/ImageEffectTest.kt");
  }

  @Test
  @TestMetadata("ImageProcessingTest.kt")
  public void testImageProcessingTest() {
    runTest("native/native.tests/testData/capi/ImageProcessingTest.kt");
  }

  @Test
  @TestMetadata("ImageTest.kt")
  public void testImageTest() {
    runTest("native/native.tests/testData/capi/ImageTest.kt");
  }

  @Test
  @TestMetadata("Image_NativeModuleTest.kt")
  public void testImage_NativeModuleTest() {
    runTest("native/native.tests/testData/capi/Image_NativeModuleTest.kt");
  }

  @Test
  @TestMetadata("InfoTest.kt")
  public void testInfoTest() {
    runTest("native/native.tests/testData/capi/InfoTest.kt");
  }

  @Test
  @TestMetadata("InitTest.kt")
  public void testInitTest() {
    runTest("native/native.tests/testData/capi/InitTest.kt");
  }

  @Test
  @TestMetadata("InputMethodTest.kt")
  public void testInputMethodTest() {
    runTest("native/native.tests/testData/capi/InputMethodTest.kt");
  }

  @Test
  @TestMetadata("InputTest.kt")
  public void testInputTest() {
    runTest("native/native.tests/testData/capi/InputTest.kt");
  }

  @Test
  @TestMetadata("JSVMTest.kt")
  public void testJSVMTest() {
    runTest("native/native.tests/testData/capi/JSVMTest.kt");
  }

  @Test
  @TestMetadata("LocationTest.kt")
  public void testLocationTest() {
    runTest("native/native.tests/testData/capi/LocationTest.kt");
  }

  @Test
  @TestMetadata("LowPowerAudioSinkTest.kt")
  public void testLowPowerAudioSinkTest() {
    runTest("native/native.tests/testData/capi/LowPowerAudioSinkTest.kt");
  }

  @Test
  @TestMetadata("LowPowerVideoSinkTest.kt")
  public void testLowPowerVideoSinkTest() {
    runTest("native/native.tests/testData/capi/LowPowerVideoSinkTest.kt");
  }

  @Test
  @TestMetadata("MediaAssetManagerTest.kt")
  public void testMediaAssetManagerTest() {
    runTest("native/native.tests/testData/capi/MediaAssetManagerTest.kt");
  }

  @Test
  @TestMetadata("MemoryTest.kt")
  public void testMemoryTest() {
    runTest("native/native.tests/testData/capi/MemoryTest.kt");
  }

  @Test
  @TestMetadata("MindSporeTest.kt")
  public void testMindSporeTest() {
    runTest("native/native.tests/testData/capi/MindSporeTest.kt");
  }

  @Test
  @TestMetadata("ModuleInstallTest.kt")
  public void testModuleInstallTest() {
    runTest("native/native.tests/testData/capi/ModuleInstallTest.kt");
  }

  @Test
  @TestMetadata("MtdTest.kt")
  public void testMtdTest() {
    runTest("native/native.tests/testData/capi/MtdTest.kt");
  }

  @Test
  @TestMetadata("Multimedia_DrmTest.kt")
  public void testMultimedia_DrmTest() {
    runTest("native/native.tests/testData/capi/Multimedia_DrmTest.kt");
  }

  @Test
  @TestMetadata("MuslMallocTest.kt")
  public void testMuslMallocTest() {
    runTest("native/native.tests/testData/capi/MuslMallocTest.kt");
  }

  @Test
  @TestMetadata("NativeColorSpaceManagerTest.kt")
  public void testNativeColorSpaceManagerTest() {
    runTest("native/native.tests/testData/capi/NativeColorSpaceManagerTest.kt");
  }

  @Test
  @TestMetadata("NativeDisplaySoloistTest.kt")
  public void testNativeDisplaySoloistTest() {
    runTest("native/native.tests/testData/capi/NativeDisplaySoloistTest.kt");
  }

  @Test
  @TestMetadata("NativeFenceTest.kt")
  public void testNativeFenceTest() {
    runTest("native/native.tests/testData/capi/NativeFenceTest.kt");
  }

  @Test
  @TestMetadata("NativeVsyncTest.kt")
  public void testNativeVsyncTest() {
    runTest("native/native.tests/testData/capi/NativeVsyncTest.kt");
  }

  @Test
  @TestMetadata("NativeWindowTest.kt")
  public void testNativeWindowTest() {
    runTest("native/native.tests/testData/capi/NativeWindowTest.kt");
  }

  @Test
  @TestMetadata("Native_BundleTest.kt")
  public void testNative_BundleTest() {
    runTest("native/native.tests/testData/capi/Native_BundleTest.kt");
  }

  @Test
  @TestMetadata("NetConnectionTest.kt")
  public void testNetConnectionTest() {
    runTest("native/native.tests/testData/capi/NetConnectionTest.kt");
  }

  @Test
  @TestMetadata("NetstackTest.kt")
  public void testNetstackTest() {
    runTest("native/native.tests/testData/capi/NetstackTest.kt");
  }

  @Test
  @TestMetadata("NetworkBoostTest.kt")
  public void testNetworkBoostTest() {
    runTest("native/native.tests/testData/capi/NetworkBoostTest.kt");
  }

  @Test
  @TestMetadata("NeuralNetworkRuntimeTest.kt")
  public void testNeuralNetworkRuntimeTest() {
    runTest("native/native.tests/testData/capi/NeuralNetworkRuntimeTest.kt");
  }

  @Test
  @TestMetadata("NotificationTest.kt")
  public void testNotificationTest() {
    runTest("native/native.tests/testData/capi/NotificationTest.kt");
  }

  @Test
  @TestMetadata("OHAVSessionTest.kt")
  public void testOHAVSessionTest() {
    runTest("native/native.tests/testData/capi/OHAVSessionTest.kt");
  }

  @Test
  @TestMetadata("OHAudioSuiteTest.kt")
  public void testOHAudioSuiteTest() {
    runTest("native/native.tests/testData/capi/OHAudioSuiteTest.kt");
  }

  @Test
  @TestMetadata("OHAudioTest.kt")
  public void testOHAudioTest() {
    runTest("native/native.tests/testData/capi/OHAudioTest.kt");
  }

  @Test
  @TestMetadata("OHIPCErrorCodeTest.kt")
  public void testOHIPCErrorCodeTest() {
    runTest("native/native.tests/testData/capi/OHIPCErrorCodeTest.kt");
  }

  @Test
  @TestMetadata("OHIPCParcelTest.kt")
  public void testOHIPCParcelTest() {
    runTest("native/native.tests/testData/capi/OHIPCParcelTest.kt");
  }

  @Test
  @TestMetadata("OHIPCRemoteObjectTest.kt")
  public void testOHIPCRemoteObjectTest() {
    runTest("native/native.tests/testData/capi/OHIPCRemoteObjectTest.kt");
  }

  @Test
  @TestMetadata("OHIPCSkeletonTest.kt")
  public void testOHIPCSkeletonTest() {
    runTest("native/native.tests/testData/capi/OHIPCSkeletonTest.kt");
  }

  @Test
  @TestMetadata("OH_BatteryInfoTest.kt")
  public void testOH_BatteryInfoTest() {
    runTest("native/native.tests/testData/capi/OH_BatteryInfoTest.kt");
  }

  @Test
  @TestMetadata("OH_CameraTest.kt")
  public void testOH_CameraTest() {
    runTest("native/native.tests/testData/capi/OH_CameraTest.kt");
  }

  @Test
  @TestMetadata("OH_CommonEventTest.kt")
  public void testOH_CommonEventTest() {
    runTest("native/native.tests/testData/capi/OH_CommonEventTest.kt");
  }

  @Test
  @TestMetadata("OH_DisplayManagerTest.kt")
  public void testOH_DisplayManagerTest() {
    runTest("native/native.tests/testData/capi/OH_DisplayManagerTest.kt");
  }

  @Test
  @TestMetadata("OH_NativeBufferTest.kt")
  public void testOH_NativeBufferTest() {
    runTest("native/native.tests/testData/capi/OH_NativeBufferTest.kt");
  }

  @Test
  @TestMetadata("OH_NativeImageTest.kt")
  public void testOH_NativeImageTest() {
    runTest("native/native.tests/testData/capi/OH_NativeImageTest.kt");
  }

  @Test
  @TestMetadata("OH_NativeXComponentTest.kt")
  public void testOH_NativeXComponentTest() {
    runTest("native/native.tests/testData/capi/OH_NativeXComponentTest.kt");
  }

  @Test
  @TestMetadata("OH_PrintTest.kt")
  public void testOH_PrintTest() {
    runTest("native/native.tests/testData/capi/OH_PrintTest.kt");
  }

  @Test
  @TestMetadata("OH_ScanTest.kt")
  public void testOH_ScanTest() {
    runTest("native/native.tests/testData/capi/OH_ScanTest.kt");
  }

  @Test
  @TestMetadata("OsAccountTest.kt")
  public void testOsAccountTest() {
    runTest("native/native.tests/testData/capi/OsAccountTest.kt");
  }

  @Test
  @TestMetadata("PasteboardTest.kt")
  public void testPasteboardTest() {
    runTest("native/native.tests/testData/capi/PasteboardTest.kt");
  }

  @Test
  @TestMetadata("PosixTest.kt")
  public void testPosixTest() {
    runTest("native/native.tests/testData/capi/PosixTest.kt");
  }

  @Test
  @TestMetadata("PreferencesTest.kt")
  public void testPreferencesTest() {
    runTest("native/native.tests/testData/capi/PreferencesTest.kt");
  }

  @Test
  @TestMetadata("PreviewTest.kt")
  public void testPreviewTest() {
    runTest("native/native.tests/testData/capi/PreviewTest.kt");
  }

  @Test
  @TestMetadata("QoSTest.kt")
  public void testQoSTest() {
    runTest("native/native.tests/testData/capi/QoSTest.kt");
  }

  @Test
  @TestMetadata("RDBTest.kt")
  public void testRDBTest() {
    runTest("native/native.tests/testData/capi/RDBTest.kt");
  }

  @Test
  @TestMetadata("RawFileTest.kt")
  public void testRawFileTest() {
    runTest("native/native.tests/testData/capi/RawFileTest.kt");
  }

  @Test
  @TestMetadata("RemoteCommunicationTest.kt")
  public void testRemoteCommunicationTest() {
    runTest("native/native.tests/testData/capi/RemoteCommunicationTest.kt");
  }

  @Test
  @TestMetadata("ResourceManagerTest.kt")
  public void testResourceManagerTest() {
    runTest("native/native.tests/testData/capi/ResourceManagerTest.kt");
  }

  @Test
  @TestMetadata("RetrievalTest.kt")
  public void testRetrievalTest() {
    runTest("native/native.tests/testData/capi/RetrievalTest.kt");
  }

  @Test
  @TestMetadata("SCSIPeripheralDDKTest.kt")
  public void testSCSIPeripheralDDKTest() {
    runTest("native/native.tests/testData/capi/SCSIPeripheralDDKTest.kt");
  }

  @Test
  @TestMetadata("SecurityAntivirusTest.kt")
  public void testSecurityAntivirusTest() {
    runTest("native/native.tests/testData/capi/SecurityAntivirusTest.kt");
  }

  @Test
  @TestMetadata("SecurityAuditTest.kt")
  public void testSecurityAuditTest() {
    runTest("native/native.tests/testData/capi/SecurityAuditTest.kt");
  }

  @Test
  @TestMetadata("SensorTest.kt")
  public void testSensorTest() {
    runTest("native/native.tests/testData/capi/SensorTest.kt");
  }

  @Test
  @TestMetadata("ServiceCollaborationTest.kt")
  public void testServiceCollaborationTest() {
    runTest("native/native.tests/testData/capi/ServiceCollaborationTest.kt");
  }

  @Test
  @TestMetadata("SoundTest.kt")
  public void testSoundTest() {
    runTest("native/native.tests/testData/capi/SoundTest.kt");
  }

  @Test
  @TestMetadata("TeeClientTest.kt")
  public void testTeeClientTest() {
    runTest("native/native.tests/testData/capi/TeeClientTest.kt");
  }

  @Test
  @TestMetadata("TelephonyTest.kt")
  public void testTelephonyTest() {
    runTest("native/native.tests/testData/capi/TelephonyTest.kt");
  }

  @Test
  @TestMetadata("TimeServiceTest.kt")
  public void testTimeServiceTest() {
    runTest("native/native.tests/testData/capi/TimeServiceTest.kt");
  }

  @Test
  @TestMetadata("TransientTaskTest.kt")
  public void testTransientTaskTest() {
    runTest("native/native.tests/testData/capi/TransientTaskTest.kt");
  }

  @Test
  @TestMetadata("UDMFTest.kt")
  public void testUDMFTest() {
    runTest("native/native.tests/testData/capi/UDMFTest.kt");
  }

  @Test
  @TestMetadata("USBSerialDDKTest.kt")
  public void testUSBSerialDDKTest() {
    runTest("native/native.tests/testData/capi/USBSerialDDKTest.kt");
  }

  @Test
  @TestMetadata("UsbDDKTest.kt")
  public void testUsbDDKTest() {
    runTest("native/native.tests/testData/capi/UsbDDKTest.kt");
  }

  @Test
  @TestMetadata("VibratorTest.kt")
  public void testVibratorTest() {
    runTest("native/native.tests/testData/capi/VibratorTest.kt");
  }

  @Test
  @TestMetadata("VideoDecoderTest.kt")
  public void testVideoDecoderTest() {
    runTest("native/native.tests/testData/capi/VideoDecoderTest.kt");
  }

  @Test
  @TestMetadata("VideoEncoderTest.kt")
  public void testVideoEncoderTest() {
    runTest("native/native.tests/testData/capi/VideoEncoderTest.kt");
  }

  @Test
  @TestMetadata("VideoProcessingTest.kt")
  public void testVideoProcessingTest() {
    runTest("native/native.tests/testData/capi/VideoProcessingTest.kt");
  }

  @Test
  @TestMetadata("VideoTest.kt")
  public void testVideoTest() {
    runTest("native/native.tests/testData/capi/VideoTest.kt");
  }

  @Test
  @TestMetadata("WebTest.kt")
  public void testWebTest() {
    runTest("native/native.tests/testData/capi/WebTest.kt");
  }

  @Test
  @TestMetadata("WifiTest.kt")
  public void testWifiTest() {
    runTest("native/native.tests/testData/capi/WifiTest.kt");
  }

  @Test
  @TestMetadata("WindowManagerTest.kt")
  public void testWindowManagerTest() {
    runTest("native/native.tests/testData/capi/WindowManagerTest.kt");
  }

  @Test
  @TestMetadata("XEngineTest.kt")
  public void testXEngineTest() {
    runTest("native/native.tests/testData/capi/XEngineTest.kt");
  }

  @Test
  @TestMetadata("ZlibTest.kt")
  public void testZlibTest() {
    runTest("native/native.tests/testData/capi/ZlibTest.kt");
  }
}
