/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.konan.test.blackbox;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Tag;
import org.jetbrains.kotlin.konan.test.blackbox.support.EnforcedProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.ClassLevelProperty;
import org.jetbrains.kotlin.konan.test.blackbox.support.group.UseStandardTestCaseGroupProvider;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateNativeTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("native/native.tests/testData/dfx")
@TestDataPath("$PROJECT_ROOT")
@Tag("dfx")
@EnforcedProperty(property = ClassLevelProperty.TEST_KIND, propertyValue = "STANDALONE")
@UseStandardTestCaseGroupProvider()
public class OhosDFXTestGenerated extends AbstractNativeBlackBoxTest {
  @Test
  public void testAllFilesPresentInDfx() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("native/native.tests/testData/dfx"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("OhosDumpMemoryTest.kt")
  public void testOhosDumpMemoryTest() {
    runTest("native/native.tests/testData/dfx/OhosDumpMemoryTest.kt");
  }

  @Test
  @TestMetadata("OhosMemDumpListenerTest.kt")
  public void testOhosMemDumpListenerTest() {
    runTest("native/native.tests/testData/dfx/OhosMemDumpListenerTest.kt");
  }

  @Test
  @TestMetadata("OhosMemDumpStripTest.kt")
  public void testOhosMemDumpStripTest() {
    runTest("native/native.tests/testData/dfx/OhosMemDumpStripTest.kt");
  }

  @Test
  @TestMetadata("OhosMemoryTraceTagTest.kt")
  public void testOhosMemoryTraceTagTest() {
    runTest("native/native.tests/testData/dfx/OhosMemoryTraceTagTest.kt");
  }

  @Test
  @TestMetadata("OomMemDumpHiAppEventTest.kt")
  public void testOomMemDumpHiAppEventTest() {
    runTest("native/native.tests/testData/dfx/OomMemDumpHiAppEventTest.kt");
  }

  @Test
  @TestMetadata("OomMemDumpLiveStressTest.kt")
  public void testOomMemDumpLiveStressTest() {
    runTest("native/native.tests/testData/dfx/OomMemDumpLiveStressTest.kt");
  }

  @Test
  @TestMetadata("ReportBacktraceToOhosLogTest.kt")
  public void testReportBacktraceToOhosLogTest() {
    runTest("native/native.tests/testData/dfx/ReportBacktraceToOhosLogTest.kt");
  }
}
